# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nestjs-app-deployment
# my-app-chart/templates/deployment.yaml
# ...
spec:
  replicas: {{ .Values.replicaCount }}
  # ...
  template:
    # ...
    spec:
      containers:
        - name: my-nestjs-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          # ...
          env:
            - name: "GREETING_MESSAGE"
              value: "{{ .Values.greetingMessage }}"