apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nestjs-release-deployment  # 릴리스 이름과 연관되도록 이름 변경 (선택사항)
spec:
  # values.yaml 파일의 replicaCount 값을 사용
  replicas: {{ .Values.replicaCount }}
  # ==========================================================
  # ===== 이 selector 부분이 누락되었을 가능성이 높습니다 =====
  # ==========================================================
  selector:
    matchLabels:
      app: my-nestjs-release-app
  # ==========================================================
  template:
    metadata:
      labels:
        # 이 labels가 위의 selector.matchLabels와 반드시 일치해야 합니다.
        app: my-nestjs-release-app
    spec:
      containers:
        - name: my-nestjs-app-container
          # values.yaml의 image.repository와 image.tag 값을 조합하여 사용
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: "GREETING_MESSAGE"
              # values.yaml의 greetingMessage 값을 사용
              value: "{{ .Values.greetingMessage }}"