apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment  # 릴리스 이름과 연관되도록 이름 변경 (선택사항)
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: my-nestjs-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: "GREETING_MESSAGE"
              value: "{{ .Values.greetingMessage }}"
            - name: "BUILD_INFO"
              value: "{{ .Values.buildInfo }}"

        # --- 2. 새로 추가하는 사이드카 컨테이너 ---
        - name: sidecar-container
          # 가장 가벼운 리눅스 이미지 중 하나인 alpine을 사용합니다.
          image: alpine:3.15
          # 이 컨테이너는 아무것도 안하고 1시간 동안 잠만 자도록 명령합니다.
          # 컨테이너가 바로 종료되지 않고 계속 살아있게 하기 위함입니다.
          command: [ "sleep", "3600" ]