apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nestjs-app-deployment
spec:
  replicas: 1 # 일단 1개의 복제본만 실행합니다.
  selector:
    matchLabels:
      app: my-nestjs-app
  template:
    metadata:
      labels:
        app: my-nestjs-app
    spec:
      containers:
        - name: my-nestjs-app-container
          # 중요: 이 부분은 젠킨스가 빌드할 때마다 동적으로 바꿀 예정입니다.
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000