apiVersion: v1
kind: Service
metadata:
  name: my-nestjs-app-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000 # Pod의 containerPort와 일치
      protocol: TCP
      name: http
  # ==========================================================
  # ===== 이 selector 부분이 가장 중요합니다! =====
  #  Deployment의 Pod 라벨(template.metadata.labels)과 반드시 일치해야 합니다.
  # ==========================================================
  selector:
    app: my-nestjs-release-app